import { motion } from 'framer-motion';
import { Brain, Cpu, MessageSquare, BarChart3, Shield, Zap, ChevronRight, Users, Star } from 'lucide-react';

interface LandingPageProps {
  onStart: () => void;
  onDocs: () => void;
}

const features = [
  {
    icon: <Brain className="w-6 h-6" />,
    title: 'AI-Powered Assessment',
    description: 'Dynamic questions generated by LLM technology adapt to your responses for a personalized evaluation.',
    color: 'from-violet-500 to-purple-600',
    bg: 'bg-violet-50',
    border: 'border-violet-200',
  },
  {
    icon: <Cpu className="w-6 h-6" />,
    title: 'Random Forest ML Model',
    description: 'Trained on 800+ student responses, our ensemble model classifies stress with high accuracy.',
    color: 'from-blue-500 to-cyan-600',
    bg: 'bg-blue-50',
    border: 'border-blue-200',
  },
  {
    icon: <MessageSquare className="w-6 h-6" />,
    title: 'Personalized Recommendations',
    description: 'GPT-powered suggestions tailored to YOUR specific stress profile and dominant issues.',
    color: 'from-emerald-500 to-green-600',
    bg: 'bg-emerald-50',
    border: 'border-emerald-200',
  },
  {
    icon: <BarChart3 className="w-6 h-6" />,
    title: 'Stress Breakdown Analytics',
    description: 'Visual breakdown of 5 key stress dimensions: emotional, sleep, academic, social & physical.',
    color: 'from-orange-500 to-amber-600',
    bg: 'bg-orange-50',
    border: 'border-orange-200',
  },
];

const pipeline = [
  { step: '01', label: 'Answer Questions', sub: 'LLM-generated adaptive chat', icon: '💬' },
  { step: '02', label: 'Score Mapping', sub: 'Rule-based feature extraction', icon: '📊' },
  { step: '03', label: 'ML Prediction', sub: 'Random Forest classification', icon: '🤖' },
  { step: '04', label: 'Get Relief Tips', sub: 'Personalized AI suggestions', icon: '💡' },
];

const stats = [
  { value: '5', label: 'Feature Dimensions', icon: '📐' },
  { value: '4', label: 'Stress Categories', icon: '🎯' },
  { value: '20', label: 'Decision Trees', icon: '🌳' },
  { value: '< 2min', label: 'Assessment Time', icon: '⚡' },
];

export default function LandingPage({ onStart, onDocs }: LandingPageProps) {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-950 to-slate-900 text-white overflow-x-hidden">
      {/* Background glow effects */}
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-purple-500/20 rounded-full blur-3xl" />
        <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-blue-500/20 rounded-full blur-3xl" />
        <div className="absolute top-1/2 left-1/2 w-64 h-64 bg-violet-500/10 rounded-full blur-3xl" />
      </div>

      {/* Nav */}
      <nav className="relative z-10 flex items-center justify-between px-6 py-5 max-w-7xl mx-auto">
        <motion.div
          initial={{ opacity: 0, x: -20 }}
          animate={{ opacity: 1, x: 0 }}
          className="flex items-center gap-2"
        >
          <div className="w-9 h-9 bg-gradient-to-br from-violet-500 to-purple-600 rounded-xl flex items-center justify-center shadow-lg shadow-purple-500/30">
            <Brain className="w-5 h-5 text-white" />
          </div>
          <span className="text-xl font-bold bg-gradient-to-r from-violet-300 to-purple-300 bg-clip-text text-transparent">
            MindEase
          </span>
          <span className="text-xs bg-violet-500/20 text-violet-300 px-2 py-0.5 rounded-full border border-violet-500/30 ml-1">
            AI
          </span>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, x: 20 }}
          animate={{ opacity: 1, x: 0 }}
          className="flex items-center gap-3"
        >
          <button
            onClick={onDocs}
            className="hidden sm:flex items-center gap-1.5 text-sm text-slate-400 hover:text-white transition-colors px-3 py-1.5 rounded-lg hover:bg-white/5"
          >
            <Shield className="w-4 h-4" /> Docs
          </button>
          <button
            onClick={onStart}
            className="flex items-center gap-2 bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-500 hover:to-purple-500 text-white text-sm font-medium px-4 py-2 rounded-xl transition-all shadow-lg shadow-purple-500/25 hover:shadow-purple-500/40"
          >
            Start Assessment <ChevronRight className="w-4 h-4" />
          </button>
        </motion.div>
      </nav>

      {/* Hero */}
      <section className="relative z-10 max-w-7xl mx-auto px-6 pt-16 pb-24 text-center">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="inline-flex items-center gap-2 bg-violet-500/10 border border-violet-500/20 rounded-full px-4 py-2 text-sm text-violet-300 mb-8">
            <Zap className="w-3.5 h-3.5 text-yellow-400" />
            Powered by Random Forest + GPT-4o Architecture
          </div>

          <h1 className="text-5xl sm:text-6xl lg:text-7xl font-extrabold mb-6 leading-tight">
            <span className="bg-gradient-to-r from-white via-violet-200 to-purple-300 bg-clip-text text-transparent">
              Detect Student
            </span>
            <br />
            <span className="bg-gradient-to-r from-violet-400 via-purple-400 to-pink-400 bg-clip-text text-transparent">
              Stress with AI
            </span>
          </h1>

          <p className="text-lg sm:text-xl text-slate-400 max-w-2xl mx-auto mb-10 leading-relaxed">
            An intelligent system that combines <strong className="text-slate-300">machine learning</strong> and{' '}
            <strong className="text-slate-300">large language models</strong> to assess your stress across 5 key
            dimensions and deliver personalized relief strategies.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <motion.button
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.97 }}
              onClick={onStart}
              className="flex items-center gap-2 bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-500 hover:to-purple-500 text-white font-semibold px-8 py-4 rounded-2xl text-base shadow-2xl shadow-purple-500/30 transition-all"
            >
              <Brain className="w-5 h-5" />
              Begin Stress Assessment
              <ChevronRight className="w-5 h-5" />
            </motion.button>
            <motion.button
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.97 }}
              onClick={onDocs}
              className="flex items-center gap-2 bg-white/5 hover:bg-white/10 border border-white/10 hover:border-white/20 text-slate-300 font-medium px-8 py-4 rounded-2xl text-base transition-all"
            >
              <Shield className="w-5 h-5" />
              View Architecture
            </motion.button>
          </div>
        </motion.div>

        {/* Stats strip */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3, duration: 0.6 }}
          className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-20 max-w-3xl mx-auto"
        >
          {stats.map((s) => (
            <div
              key={s.label}
              className="bg-white/5 border border-white/10 rounded-2xl p-4 backdrop-blur-sm"
            >
              <div className="text-2xl mb-1">{s.icon}</div>
              <div className="text-2xl font-bold text-white">{s.value}</div>
              <div className="text-xs text-slate-400 mt-0.5">{s.label}</div>
            </div>
          ))}
        </motion.div>
      </section>

      {/* Pipeline */}
      <section className="relative z-10 max-w-7xl mx-auto px-6 py-20">
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="text-center mb-14"
        >
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">
            How the System Works
          </h2>
          <p className="text-slate-400 max-w-xl mx-auto">
            A 4-step intelligent pipeline from adaptive questioning to personalized recommendations
          </p>
        </motion.div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {pipeline.map((p, i) => (
            <motion.div
              key={p.step}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="relative bg-white/5 border border-white/10 rounded-2xl p-6 hover:bg-white/8 transition-colors group"
            >
              {i < 3 && (
                <div className="hidden lg:block absolute top-1/2 -right-3 transform -translate-y-1/2 z-10">
                  <ChevronRight className="w-5 h-5 text-violet-400/50" />
                </div>
              )}
              <div className="text-3xl mb-4">{p.icon}</div>
              <div className="text-xs font-mono text-violet-400 mb-1">{p.step}</div>
              <div className="font-semibold text-white mb-1">{p.label}</div>
              <div className="text-sm text-slate-400">{p.sub}</div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* Features */}
      <section className="relative z-10 max-w-7xl mx-auto px-6 py-20">
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="text-center mb-14"
        >
          <h2 className="text-3xl sm:text-4xl font-bold text-white mb-4">System Capabilities</h2>
          <p className="text-slate-400 max-w-xl mx-auto">
            Built with production-grade ML and LLM architecture for a college-level AI project
          </p>
        </motion.div>

        <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          {features.map((f, i) => (
            <motion.div
              key={f.title}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: i * 0.1 }}
              className="bg-white/5 border border-white/10 rounded-2xl p-6 hover:bg-white/8 transition-all group"
            >
              <div className={`w-12 h-12 bg-gradient-to-br ${f.color} rounded-xl flex items-center justify-center text-white mb-4 shadow-lg`}>
                {f.icon}
              </div>
              <h3 className="text-lg font-semibold text-white mb-2">{f.title}</h3>
              <p className="text-sm text-slate-400 leading-relaxed">{f.description}</p>
            </motion.div>
          ))}
        </div>
      </section>

      {/* 5 Features Schema */}
      <section className="relative z-10 max-w-7xl mx-auto px-6 py-20">
        <motion.div
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          className="bg-white/5 border border-white/10 rounded-3xl p-8 sm:p-12 backdrop-blur-sm"
        >
          <div className="text-center mb-10">
            <h2 className="text-2xl sm:text-3xl font-bold text-white mb-3">Core Feature Schema</h2>
            <p className="text-slate-400">Fixed 5-dimensional stress measurement framework</p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-5 gap-4">
            {[
              { key: 'stress_emotional', label: 'Emotional Stress', emoji: '🧠', color: 'from-orange-400 to-red-500' },
              { key: 'sleep_quality', label: 'Sleep Quality', emoji: '🌙', color: 'from-violet-400 to-purple-500' },
              { key: 'academic_pressure', label: 'Academic Pressure', emoji: '📚', color: 'from-red-400 to-rose-500' },
              { key: 'social_interaction', label: 'Social Interaction', emoji: '🤝', color: 'from-cyan-400 to-blue-500' },
              { key: 'physical_activity', label: 'Physical Activity', emoji: '🏃', color: 'from-green-400 to-emerald-500' },
            ].map((f) => (
              <div key={f.key} className="bg-white/5 border border-white/10 rounded-2xl p-4 text-center">
                <div className="text-3xl mb-2">{f.emoji}</div>
                <div className="text-xs font-mono text-slate-500 mb-1">{f.key}</div>
                <div className="text-sm font-medium text-slate-300">{f.label}</div>
                <div className="mt-2 text-xs text-slate-500">Scale: 1–5</div>
              </div>
            ))}
          </div>

          <div className="mt-8 bg-slate-900/50 rounded-xl p-4 font-mono text-sm overflow-x-auto border border-white/5">
            <div className="text-slate-500 mb-1">{'// ML Model Input Vector'}</div>
            <div className="text-green-400">{'{'}</div>
            <div className="text-slate-300 ml-4">
              {'"stress_emotional": '}<span className="text-amber-400">3</span>{','}
            </div>
            <div className="text-slate-300 ml-4">
              {'"sleep_quality": '}<span className="text-amber-400">4</span>{','}
            </div>
            <div className="text-slate-300 ml-4">
              {'"academic_pressure": '}<span className="text-amber-400">5</span>{','}
            </div>
            <div className="text-slate-300 ml-4">
              {'"social_interaction": '}<span className="text-amber-400">2</span>{','}
            </div>
            <div className="text-slate-300 ml-4">
              {'"physical_activity": '}<span className="text-amber-400">2</span>
            </div>
            <div className="text-green-400">{'}'}</div>
            <div className="text-slate-500 mt-2">{'// → Random Forest → "High" (conf: 0.82)'}</div>
          </div>
        </motion.div>
      </section>

      {/* CTA */}
      <section className="relative z-10 max-w-4xl mx-auto px-6 py-20 text-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="bg-gradient-to-br from-violet-900/50 to-purple-900/50 border border-violet-500/20 rounded-3xl p-12"
        >
          <div className="text-4xl mb-4">🎓</div>
          <h2 className="text-3xl font-bold text-white mb-4">Ready to Check Your Stress?</h2>
          <p className="text-slate-400 mb-8 max-w-lg mx-auto">
            Takes less than 2 minutes. Completely private. Get your personalized stress analysis powered by AI.
          </p>
          <div className="flex items-center justify-center gap-4 mb-6">
            <div className="flex items-center gap-1 text-sm text-slate-400">
              <Users className="w-4 h-4 text-violet-400" />
              <span>Private & Anonymous</span>
            </div>
            <div className="flex items-center gap-1 text-sm text-slate-400">
              <Star className="w-4 h-4 text-amber-400" />
              <span>AI-Powered</span>
            </div>
            <div className="flex items-center gap-1 text-sm text-slate-400">
              <Zap className="w-4 h-4 text-green-400" />
              <span>Instant Results</span>
            </div>
          </div>
          <motion.button
            whileHover={{ scale: 1.03 }}
            whileTap={{ scale: 0.97 }}
            onClick={onStart}
            className="bg-gradient-to-r from-violet-600 to-purple-600 hover:from-violet-500 hover:to-purple-500 text-white font-bold px-10 py-4 rounded-2xl text-lg shadow-2xl shadow-purple-500/30 transition-all"
          >
            Start Free Assessment →
          </motion.button>
        </motion.div>
      </section>

      {/* Footer */}
      <footer className="relative z-10 border-t border-white/5 px-6 py-8 text-center text-slate-500 text-sm">
        <div className="flex items-center justify-center gap-2 mb-2">
          <Brain className="w-4 h-4 text-violet-400" />
          <span className="text-white font-medium">MindEase</span>
          <span>– Student Stress Detection & Relief System</span>
        </div>
        <p>Built with React + TypeScript + Tailwind CSS | ML: Random Forest | LLM: GPT-4o Architecture</p>
      </footer>
    </div>
  );
}
